// ============================================================
// lib/data.ts — Product data, categories, brands, reviews, promo codes
// Migrated from data/products.js + new data for landing page
// ============================================================

import { Product, Order, PromoCode } from "@/types";

export const CATEGORIES = [
  "All",
  "Electronics",
  "Clothing",
  "Home & Living",
  "Sports",
  "Books",
  "Beauty",
] as const;

export type Category = (typeof CATEGORIES)[number];

export const PROMO_CODES: PromoCode[] = [
  { code: "WELCOME10", discount: 10, minOrder: 50 },
  { code: "SAVE20", discount: 20, minOrder: 100 },
  { code: "VIP30", discount: 30, minOrder: 200 },
];

export const products: Product[] = [
  {
    id: 1,
    name: "AirPods Pro Max",
    category: "Electronics",
    price: 549.99,
    description: "Premium over-ear headphones with active noise cancellation, spatial audio, and 20-hour battery life.",
    image: "https://images.unsplash.com/photo-1583394838336-acd977736f90?w=400&q=80",
    rating: 4.8,
    badge: "Best Seller",
    stock: 24,
    specs: { "Battery": "20 hours", "Noise Cancellation": "Active", "Connectivity": "Bluetooth 5.3", "Weight": "384g" },
  },
  {
    id: 2,
    name: "Minimal Ceramic Watch",
    category: "Electronics",
    price: 320.0,
    description: "Sleek ceramic-finish smartwatch with health monitoring, GPS, and 48-hour battery endurance.",
    image: "https://images.unsplash.com/photo-1523275335684-37898b6baf30?w=400&q=80",
    rating: 4.6,
    badge: "New",
    stock: 18,
    specs: { "Display": "1.4\" AMOLED", "Battery": "48 hours", "Water Resistance": "5ATM", "Sensors": "Heart Rate, SpO2, GPS" },
  },
  {
    id: 3,
    name: "Matte Black Laptop",
    category: "Electronics",
    price: 1299.99,
    description: "Ultra-thin 14-inch laptop with M3 chip, 16GB RAM, 512GB SSD, and a stunning OLED display.",
    image: "https://images.unsplash.com/photo-1496181133206-80ce9b88a853?w=400&q=80",
    rating: 4.9,
    badge: "Top Pick",
    stock: 12,
    specs: { "Processor": "M3 Chip", "RAM": "16GB", "Storage": "512GB SSD", "Display": "14\" OLED" },
  },
  {
    id: 4,
    name: "Minimalist Linen Blazer",
    category: "Clothing",
    price: 189.0,
    description: "Breathable linen-cotton blend blazer with a tailored fit, perfect for smart-casual occasions.",
    image: "https://images.unsplash.com/photo-1594938298603-c8148c4b4a97?w=400&q=80",
    rating: 4.4,
    badge: null,
    stock: 30,
    specs: { "Material": "Linen-Cotton Blend", "Fit": "Tailored", "Care": "Dry Clean Only" },
  },
  {
    id: 5,
    name: "Oversized Graphic Tee",
    category: "Clothing",
    price: 42.0,
    description: "100% organic cotton oversized tee with artistic print, available in 8 colourways.",
    image: "https://images.unsplash.com/photo-1521572163474-6864f9cf17ab?w=400&q=80",
    rating: 4.3,
    badge: "Sale",
    stock: 56,
    specs: { "Material": "100% Organic Cotton", "Fit": "Oversized", "Sizes": "XS–3XL" },
  },
  {
    id: 6,
    name: "Premium Yoga Leggings",
    category: "Sports",
    price: 98.0,
    description: "High-waist compression leggings with moisture-wicking fabric and hidden pocket.",
    image: "https://images.unsplash.com/photo-1506629082955-511b1aa562c8?w=400&q=80",
    rating: 4.7,
    badge: null,
    stock: 42,
    specs: { "Material": "Nylon/Spandex", "Waist": "High-rise", "Features": "Moisture-wicking, Hidden pocket" },
  },
  {
    id: 7,
    name: "Artisan Ceramic Vase",
    category: "Home & Living",
    price: 76.0,
    description: "Hand-thrown stoneware vase with a reactive glaze finish — each piece is beautifully unique.",
    image: "https://images.unsplash.com/photo-1602173574767-37ac01994b2a?w=400&q=80",
    rating: 4.5,
    badge: "Handmade",
    stock: 15,
    specs: { "Material": "Stoneware", "Height": "12 inches", "Finish": "Reactive Glaze" },
  },
  {
    id: 8,
    name: "Scented Soy Candle Set",
    category: "Home & Living",
    price: 54.0,
    description: "Set of 3 hand-poured soy candles in amber glass jars — notes of cedarwood, vanilla, and sage.",
    image: "https://images.unsplash.com/photo-1603905627407-a2fc5a7cc547?w=400&q=80",
    rating: 4.6,
    badge: "Gift Idea",
    stock: 38,
    specs: { "Type": "Soy Wax", "Burn Time": "45 hours each", "Scents": "Cedarwood, Vanilla, Sage" },
  },
  {
    id: 9,
    name: "Carbon Fibre Water Bottle",
    category: "Sports",
    price: 64.0,
    description: "Vacuum-insulated 32oz bottle keeps drinks cold 24h, hot 12h. BPA-free and leak-proof.",
    image: "https://images.unsplash.com/photo-1602143407151-7111542de6e8?w=400&q=80",
    rating: 4.7,
    badge: "Eco",
    stock: 65,
    specs: { "Capacity": "32oz / 950ml", "Insulation": "Double-wall vacuum", "Material": "BPA-free Steel" },
  },
  {
    id: 10,
    name: "Atomic Habits",
    category: "Books",
    price: 18.99,
    description: "James Clear's international bestseller on building good habits and breaking bad ones.",
    image: "https://images.unsplash.com/photo-1544716278-ca5e3f4abd8c?w=400&q=80",
    rating: 4.9,
    badge: "Bestseller",
    stock: 120,
    specs: { "Author": "James Clear", "Pages": "320", "Format": "Paperback", "Language": "English" },
  },
  {
    id: 11,
    name: "Deep Work",
    category: "Books",
    price: 16.49,
    description: "Cal Newport's guide to focused success in a distracted world. A must-read for professionals.",
    image: "https://images.unsplash.com/photo-1481627834876-b7833e8f5570?w=400&q=80",
    rating: 4.7,
    badge: null,
    stock: 85,
    specs: { "Author": "Cal Newport", "Pages": "296", "Format": "Paperback", "Language": "English" },
  },
  {
    id: 12,
    name: "Vitamin C Glow Serum",
    category: "Beauty",
    price: 48.0,
    description: "15% Vitamin C serum with hyaluronic acid and niacinamide for radiant, even-toned skin.",
    image: "https://images.unsplash.com/photo-1620916566398-39f1143ab7be?w=400&q=80",
    rating: 4.6,
    badge: "Editor's Pick",
    stock: 50,
    specs: { "Volume": "30ml", "Key Ingredients": "15% Vitamin C, Hyaluronic Acid, Niacinamide", "Skin Type": "All" },
  },
  {
    id: 13,
    name: "Matte Lip Collection",
    category: "Beauty",
    price: 32.0,
    description: "Set of 6 long-wearing matte liquid lipsticks in curated nude and berry shades.",
    image: "https://images.unsplash.com/photo-1586495777744-4e6232bf2e54?w=400&q=80",
    rating: 4.4,
    badge: "New",
    stock: 44,
    specs: { "Contents": "6 shades", "Finish": "Matte", "Longevity": "12 hours" },
  },
  {
    id: 14,
    name: "Smart LED Desk Lamp",
    category: "Home & Living",
    price: 89.0,
    description: "Touch-control LED lamp with 5 colour temperatures, wireless charging pad, and USB-A port.",
    image: "https://images.unsplash.com/photo-1507473885765-e6ed057f782c?w=400&q=80",
    rating: 4.5,
    badge: null,
    stock: 22,
    specs: { "Modes": "5 colour temperatures", "Features": "Wireless charging, USB-A", "Control": "Touch" },
  },
];

export const FEATURED_BRANDS = [
  { name: "Apple", logo: "🍎" },
  { name: "Nike", logo: "✓" },
  { name: "Samsung", logo: "📱" },
  { name: "Sony", logo: "🎵" },
  { name: "Adidas", logo: "⚡" },
  { name: "Dyson", logo: "🌀" },
];

export const CUSTOMER_REVIEWS = [
  {
    id: 1,
    name: "Sarah Mitchell",
    avatar: "👩‍💼",
    rating: 5,
    text: "ShopFlow completely transformed my online shopping experience. The interface is beautiful and the checkout process is seamless.",
    date: "2 weeks ago",
  },
  {
    id: 2,
    name: "David Chen",
    avatar: "👨‍💻",
    rating: 5,
    text: "As a developer, I appreciate the attention to detail in this platform. Fast, responsive, and a joy to use on any device.",
    date: "1 month ago",
  },
  {
    id: 3,
    name: "Emily Roberts",
    avatar: "👩‍🎨",
    rating: 4,
    text: "Love the dark mode and the product recommendations. Found exactly what I was looking for within minutes!",
    date: "3 weeks ago",
  },
];

export const DEMO_ORDERS: Order[] = [
  {
    id: "SF-2024-001",
    date: "2024-12-15",
    items: [
      { ...products[0], qty: 1 },
      { ...products[9], qty: 2 },
    ],
    subtotal: 587.97,
    shipping: 0,
    tax: 47.04,
    total: 635.01,
    status: "delivered",
    address: { fullName: "Alex Johnson", street: "123 Main St", city: "San Francisco", state: "CA", zip: "94105", country: "US", phone: "+1 555-0123" },
  },
  {
    id: "SF-2024-002",
    date: "2025-01-08",
    items: [
      { ...products[4], qty: 3 },
      { ...products[7], qty: 1 },
    ],
    subtotal: 180.0,
    shipping: 0,
    tax: 14.4,
    total: 194.4,
    status: "shipped",
    address: { fullName: "Alex Johnson", street: "123 Main St", city: "San Francisco", state: "CA", zip: "94105", country: "US", phone: "+1 555-0123" },
  },
  {
    id: "SF-2025-003",
    date: "2025-06-28",
    items: [
      { ...products[2], qty: 1 },
    ],
    subtotal: 1299.99,
    shipping: 0,
    tax: 104.0,
    total: 1403.99,
    status: "processing",
    address: { fullName: "Alex Johnson", street: "123 Main St", city: "San Francisco", state: "CA", zip: "94105", country: "US", phone: "+1 555-0123" },
  },
];
